/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    edit_history: EditHistory;
    nummernkreise: Nummernkreise;
    email_queue: EmailQueue;
    pdf_uploads: PdfUpload;
    produkttypen: Produkttypen;
    materialien: Materialien;
    profile: Profile;
    fluegelanzahl: Fluegelanzahl;
    zusatzlichter: Zusatzlichter;
    oeffnungsarten: Oeffnungsarten;
    fensterformen: Fensterform;
    farben: Farben;
    dichtungsfarben: Dichtungsfarben;
    verglasungen: Verglasungen;
    schallschutz: Schallschutz;
    sicherheitsglas: Sicherheitsglas;
    glasdekore: Glasdekore;
    sprossen: Sprossen;
    extras: Extra;
    preisregeln: Preisregeln;
    rabattcodes: Rabattcode;
    anfragen: Anfragen;
    status_historie: StatusHistorie;
    rechnungen: Rechnungen;
    angebote: Angebote;
    reklamationen: Reklamationen;
    'puck-templates': PuckTemplate;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    edit_history: EditHistorySelect<false> | EditHistorySelect<true>;
    nummernkreise: NummernkreiseSelect<false> | NummernkreiseSelect<true>;
    email_queue: EmailQueueSelect<false> | EmailQueueSelect<true>;
    pdf_uploads: PdfUploadsSelect<false> | PdfUploadsSelect<true>;
    produkttypen: ProdukttypenSelect<false> | ProdukttypenSelect<true>;
    materialien: MaterialienSelect<false> | MaterialienSelect<true>;
    profile: ProfileSelect<false> | ProfileSelect<true>;
    fluegelanzahl: FluegelanzahlSelect<false> | FluegelanzahlSelect<true>;
    zusatzlichter: ZusatzlichterSelect<false> | ZusatzlichterSelect<true>;
    oeffnungsarten: OeffnungsartenSelect<false> | OeffnungsartenSelect<true>;
    fensterformen: FensterformenSelect<false> | FensterformenSelect<true>;
    farben: FarbenSelect<false> | FarbenSelect<true>;
    dichtungsfarben: DichtungsfarbenSelect<false> | DichtungsfarbenSelect<true>;
    verglasungen: VerglasungenSelect<false> | VerglasungenSelect<true>;
    schallschutz: SchallschutzSelect<false> | SchallschutzSelect<true>;
    sicherheitsglas: SicherheitsglasSelect<false> | SicherheitsglasSelect<true>;
    glasdekore: GlasdekoreSelect<false> | GlasdekoreSelect<true>;
    sprossen: SprossenSelect<false> | SprossenSelect<true>;
    extras: ExtrasSelect<false> | ExtrasSelect<true>;
    preisregeln: PreisregelnSelect<false> | PreisregelnSelect<true>;
    rabattcodes: RabattcodesSelect<false> | RabattcodesSelect<true>;
    anfragen: AnfragenSelect<false> | AnfragenSelect<true>;
    status_historie: StatusHistorieSelect<false> | StatusHistorieSelect<true>;
    rechnungen: RechnungenSelect<false> | RechnungenSelect<true>;
    angebote: AngeboteSelect<false> | AngeboteSelect<true>;
    reklamationen: ReklamationenSelect<false> | ReklamationenSelect<true>;
    'puck-templates': PuckTemplatesSelect<false> | PuckTemplatesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  vorname?: string | null;
  nachname?: string | null;
  rolle?: ('admin' | 'mitarbeiter' | 'viewer' | 'kunde') | null;
  /**
   * Automatisch bei Checkout erstellt
   */
  stripe_customer_id?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit_history".
 */
export interface EditHistory {
  id: string;
  collection: string;
  doc_id: string;
  event: string;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  editor?: (string | null) | User;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nummernkreise".
 */
export interface Nummernkreise {
  id: string;
  typ: 'ANG' | 'RE' | 'GS';
  jahr: number;
  letzte_nummer: number;
  prefix: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_queue".
 */
export interface EmailQueue {
  id: string;
  event_type: string;
  to: string;
  subject: string;
  html?: string | null;
  plain_text?: string | null;
  reply_to?: string | null;
  payload_data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'pending' | 'processing' | 'sent' | 'failed' | 'dead' | 'skipped';
  attempts?: number | null;
  max_attempts?: number | null;
  next_retry_at?: string | null;
  idempotency_key: string;
  error_log?: string | null;
  /**
   * Zugehoerige Anfrage (fuer Tab-Filterung)
   */
  anfrage?: (string | null) | Anfragen;
  /**
   * Manuell gesendet von (null bei automatischen)
   */
  sent_by?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anfragen".
 */
export interface Anfragen {
  id: string;
  anfrage_nummer: string;
  status?:
    | (
        | 'neu'
        | 'in_bearbeitung'
        | 'angebot_versendet'
        | 'bestaetigt'
        | 'zahlungslink_versendet'
        | 'bezahlt'
        | 'an_hersteller'
        | 'hersteller_bestaetigt'
        | 'hersteller_bestaetigt_mit_vorbehalt'
        | 'in_produktion'
        | 'hersteller_problem'
        | 'versandbereit'
        | 'geliefert'
        | 'abgeschlossen'
        | 'rueckfrage'
        | 'abgelehnt'
        | 'storniert'
        | 'zahlungsproblem'
        | 'wieder_geoeffnet'
        | 'reklamation'
        | 'rueckerstattung_ausstehend'
        | 'rueckerstattung_abgeschlossen'
        | 'kundenantwort'
        | 'stornierung_beantragt'
      )
    | null;
  /**
   * Wird automatisch bei jedem Statuswechsel aktualisiert.
   */
  last_status_change_at?: string | null;
  produkte?:
    | {
        produkttyp?: string | null;
        material?: string | null;
        profil?: string | null;
        masse_breite?: number | null;
        masse_hoehe?: number | null;
        fluegelanzahl?: string | null;
        farbe_aussen?: string | null;
        farbe_innen?: string | null;
        verglasung?: string | null;
        weitere_optionen?: string | null;
        stueckzahl?: number | null;
        einzelpreis?: number | null;
        konfiguration_snapshot?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  kontaktdaten?: {
    vorname?: string | null;
    nachname?: string | null;
    email?: string | null;
    telefon?: string | null;
    strasse?: string | null;
    plz?: string | null;
    ort?: string | null;
    nachricht?: string | null;
  };
  gesamtpreis?: number | null;
  rabattcode?: (string | null) | Rabattcode;
  hersteller_bestellnummer?: string | null;
  lieferdatum_erwartet?: string | null;
  hersteller_notizen?: string | null;
  hersteller_antwort?: string | null;
  stornierung_grund?: string | null;
  rueckerstattung_betrag?: number | null;
  rueckerstattung_status?: ('ausstehend' | 'durchgefuehrt' | 'abgelehnt') | null;
  /**
   * Wird bei Statusänderung als Kommentar gespeichert
   */
  _status_kommentar?: string | null;
  /**
   * Manuelle Änderungen werden hier automatisch protokolliert.
   */
  interne_notizen?: string | null;
  /**
   * Wird automatisch bei jeder Aenderung erhoeht.
   */
  version?: number | null;
  /**
   * Aktuelle Stripe Checkout Session URL
   */
  stripe_checkout_url?: string | null;
  /**
   * Stripe Checkout Session ID
   */
  stripe_session_id?: string | null;
  /**
   * Stripe Payment Intent ID (nach Zahlung)
   */
  stripe_payment_intent_id?: string | null;
  stripe_payment_status?:
    | ('offen' | 'bezahlt' | 'abgelaufen' | 'dispute' | 'rueckerstattet' | 'teilweise_erstattet')
    | null;
  stripe_expires_at?: string | null;
  /**
   * Kumulierter Erstattungsbetrag in Cent
   */
  stripe_refunded_amount_cents?: number | null;
  /**
   * Zeitstempel der AGB-Akzeptanz bei Anfrage-Formular
   */
  agb_akzeptiert_am?: string | null;
  /**
   * Zeitstempel der AGB-Akzeptanz bei Angebots-Annahme
   */
  agb_akzeptiert_bei_annahme_am?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rabattcodes".
 */
export interface Rabattcode {
  id: string;
  code: string;
  beschreibung?: string | null;
  typ: 'prozent' | 'festbetrag';
  wert: number;
  min_bestellwert?: number | null;
  gueltig_von?: string | null;
  gueltig_bis?: string | null;
  max_nutzungen?: number | null;
  aktuelle_nutzungen?: number | null;
  aktiv?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf_uploads".
 */
export interface PdfUpload {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produkttypen".
 */
export interface Produkttypen {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  erlaubte_materialien?: (string | Materialien)[] | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materialien".
 */
export interface Materialien {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  lieferzeit_wochen?: number | null;
  garantie_jahre?: number | null;
  erlaubte_profile?: (string | Profile)[] | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: string;
  name_technisch: string;
  name_einfach: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  qualitaetsstufe?: ('einstieg' | 'standard' | 'premium' | 'top') | null;
  technische_daten?: {
    uw_wert?: number | null;
    kammern?: number | null;
    bautiefe_mm?: number | null;
    dichtungen?: number | null;
  };
  masse?: {
    min_breite_mm?: number | null;
    max_breite_mm?: number | null;
    min_hoehe_mm?: number | null;
    max_hoehe_mm?: number | null;
  };
  material: string | Materialien;
  /**
   * Welche Produkttypen können mit diesem Profil konfiguriert werden? Leer = keine Einschränkung.
   */
  erlaubte_produkttypen?: (string | Produkttypen)[] | null;
  /**
   * Welche Fensterformen sind für dieses Profil verfügbar? Leer = alle aktiven Formen.
   */
  erlaubte_fensterformen?: (string | Fensterform)[] | null;
  /**
   * Welche Flügelanzahlen sind möglich? Leer = alle aktiven Optionen.
   */
  erlaubte_fluegelanzahl?: (string | Fluegelanzahl)[] | null;
  /**
   * Welche Öffnungsarten unterstützt dieses Profil? Leer = alle aktiven Arten.
   */
  erlaubte_oeffnungsarten?: (string | Oeffnungsarten)[] | null;
  /**
   * Welche Zusatzlichter (Ober-/Unterlicht) sind möglich? Leer = alle aktiven Optionen.
   */
  erlaubte_zusatzlichter?: (string | Zusatzlichter)[] | null;
  /**
   * Welche Farben sind für dieses Profil erlaubt? Leer = Fallback auf Material-Filter.
   */
  erlaubte_farben?: (string | Farben)[] | null;
  /**
   * Welche Dichtungsfarben stehen zur Auswahl? Leer = alle aktiven Dichtungsfarben.
   */
  erlaubte_dichtungsfarben?: (string | Dichtungsfarben)[] | null;
  /**
   * Welche Verglasungsoptionen sind verfügbar? Leer = alle aktiven Verglasungen.
   */
  erlaubte_verglasungen?: (string | Verglasungen)[] | null;
  /**
   * Welche Schallschutz-Optionen bietet dieses Profil? Leer = alle aktiven Optionen.
   */
  erlaubte_schallschutz?: (string | Schallschutz)[] | null;
  /**
   * Welches Sicherheitsglas ist verfügbar? Leer = alle aktiven Optionen.
   */
  erlaubte_sicherheitsglas?: (string | Sicherheitsglas)[] | null;
  /**
   * Welche Glasdekore können gewählt werden? Leer = alle aktiven Dekore.
   */
  erlaubte_glasdekore?: (string | Glasdekore)[] | null;
  /**
   * Welche Sprossentypen sind möglich? Leer = alle aktiven Sprossen.
   */
  erlaubte_sprossen?: (string | Sprossen)[] | null;
  /**
   * Welche Extras (Griffe, Beschläge) sind verfügbar? Leer = alle aktiven Extras.
   */
  erlaubte_extras?: (string | Extra)[] | null;
  last_edited_by?: (string | null) | User;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fensterformen".
 */
export interface Fensterform {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  erlaubte_fluegelanzahl?: (string | Fluegelanzahl)[] | null;
  erlaubte_oeffnungsarten?: (string | Oeffnungsarten)[] | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fluegelanzahl".
 */
export interface Fluegelanzahl {
  id: string;
  name: string;
  slug: string;
  anzahl: number;
  fuer_produkttypen?: (string | Produkttypen)[] | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oeffnungsarten".
 */
export interface Oeffnungsarten {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  fuer_fenster?: boolean | null;
  fuer_balkontuer?: boolean | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zusatzlichter".
 */
export interface Zusatzlichter {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  kombinierbar_mit?: (string | Fluegelanzahl)[] | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "farben".
 */
export interface Farben {
  id: string;
  name: string;
  slug: string;
  kategorie: 'standard' | 'dekor' | 'uni' | 'ral_sonderfarbe';
  ral_code?: string | null;
  farb_code?: string | null;
  bild?: (string | null) | Media;
  fuer_aussen?: boolean | null;
  fuer_innen?: boolean | null;
  erlaubte_materialien?: (string | Materialien)[] | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dichtungsfarben".
 */
export interface Dichtungsfarben {
  id: string;
  name: string;
  slug: string;
  farb_code?: string | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verglasungen".
 */
export interface Verglasungen {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  ug_wert?: number | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schallschutz".
 */
export interface Schallschutz {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  schallschutzklasse?: number | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sicherheitsglas".
 */
export interface Sicherheitsglas {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  typ?: ('vsg_aussen' | 'vsg_innen' | 'vsg_beidseitig') | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glasdekore".
 */
export interface Glasdekore {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sprossen".
 */
export interface Sprossen {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  typ?: ('wiener' | 'helima' | 'aufgesetzt') | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras".
 */
export interface Extra {
  id: string;
  name: string;
  slug: string;
  beschreibung?: string | null;
  bild?: (string | null) | Media;
  kategorie?: ('griffe' | 'beschlaege' | 'sonstiges') | null;
  aufpreis?: number | null;
  aktiv?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preisregeln".
 */
export interface Preisregeln {
  id: string;
  name: string;
  produkttyp?: (string | null) | Produkttypen;
  material?: (string | null) | Materialien;
  profil?: (string | null) | Profile;
  grundpreis_pro_m2: number;
  aufpreis_typ?: ('pauschal' | 'pro_m2') | null;
  aufpreis_wert?: number | null;
  beschreibung?: string | null;
  aktiv?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status_historie".
 */
export interface StatusHistorie {
  id: string;
  anfrage: string | Anfragen;
  von_status: string;
  zu_status: string;
  geaendert_von?: (string | null) | User;
  zeitpunkt: string;
  kommentar?: string | null;
  /**
   * Optionale Datei-Anhaenge (z.B. Kundenantwort-Dateien)
   */
  anhaenge?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechnungen".
 */
export interface Rechnungen {
  id: string;
  typ: 'rechnung' | 'gutschrift';
  /**
   * RE-YYYY-NNNN oder GS-YYYY-NNNN
   */
  nummer: string;
  anfrage: string | Anfragen;
  anfrage_nummer: string;
  pdf: string | PdfUpload;
  betrag_netto_cents: number;
  betrag_brutto_cents: number;
  mwst_cents: number;
  mwst_satz: number;
  original_rechnung?: (string | null) | Rechnungen;
  original_rechnung_nummer?: string | null;
  original_rechnung_datum?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote".
 */
export interface Angebote {
  id: string;
  /**
   * ANG-YYYY-NNNN
   */
  nummer: string;
  /**
   * Versionsnummer (1, 2, 3...)
   */
  version: number;
  anfrage: string | Anfragen;
  anfrage_nummer: string;
  status: 'entwurf' | 'versendet';
  gueltig_bis?: string | null;
  freitext?: string | null;
  pdf: string | PdfUpload;
  betrag_netto_cents: number;
  betrag_brutto_cents: number;
  mwst_cents: number;
  mwst_satz: number;
  /**
   * Pflicht wenn Preis vom berechneten Wert abweicht
   */
  preisanpassung_begruendung?: string | null;
  /**
   * Array mit { positionsIndex, bruttoCents } fuer individuell angepasste Positionen
   */
  preisanpassung_positionen?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Differenz wenn Gesamtpreis manuell unter Einzelpreis-Summe gesetzt wurde
   */
  rabatt_cents?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reklamationen".
 */
export interface Reklamationen {
  id: string;
  anfrage: string | Anfragen;
  beschreibung: string;
  /**
   * Max. 5 Dateien, max. 10 MB pro Datei
   */
  fotos?: (string | Media)[] | null;
  status: 'offen' | 'in_bearbeitung' | 'geloest';
  /**
   * Nur fuer Admin/Mitarbeiter -- Loesung beschreiben
   */
  loesung?: string | null;
  erstellt_von?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable component templates for the visual editor
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates".
 */
export interface PuckTemplate {
  id: string;
  /**
   * A descriptive name for this template
   */
  name: string;
  /**
   * Optional description of what this template contains
   */
  description?: string | null;
  /**
   * Category for organizing templates (e.g., "Hero", "Footer", "CTA")
   */
  category?: string | null;
  /**
   * Serialized Puck component data
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional thumbnail URL for template preview
   */
  thumbnail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page (auto-generated from title)
   */
  slug: string;
  /**
   * Overall page structure and layout style
   */
  pageLayout: 'default' | 'landing' | 'full-width';
  /**
   * Which editor was used to create this page
   */
  editorVersion?: ('legacy' | 'puck') | null;
  /**
   * Mark this page as the homepage
   */
  isHomepage?: boolean | null;
  /**
   * Puck editor data - managed via visual editor
   */
  puckData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  meta?: {
    /**
     * Override the page title for search engines
     */
    title?: string | null;
    /**
     * Description shown in search engine results
     */
    description?: string | null;
    /**
     * Image shown when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * Prevent search engines from indexing this page
     */
    noindex?: boolean | null;
    /**
     * Prevent search engines from following links on this page
     */
    nofollow?: boolean | null;
    /**
     * Exclude this page from the XML sitemap
     */
    excludeFromSitemap?: boolean | null;
  };
  /**
   * Configure conversion tracking for analytics
   */
  conversionTracking?: {
    /**
     * Check this if this page represents a completed conversion (e.g., thank you page)
     */
    isConversionPage?: boolean | null;
    /**
     * Type of conversion this page represents
     */
    conversionType?: ('lead' | 'registration' | 'purchase' | 'donation' | 'newsletter' | 'contact' | 'custom') | null;
    /**
     * Monetary value of this conversion (0 for non-monetary conversions)
     */
    conversionValue?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'edit_history';
        value: string | EditHistory;
      } | null)
    | ({
        relationTo: 'nummernkreise';
        value: string | Nummernkreise;
      } | null)
    | ({
        relationTo: 'email_queue';
        value: string | EmailQueue;
      } | null)
    | ({
        relationTo: 'pdf_uploads';
        value: string | PdfUpload;
      } | null)
    | ({
        relationTo: 'produkttypen';
        value: string | Produkttypen;
      } | null)
    | ({
        relationTo: 'materialien';
        value: string | Materialien;
      } | null)
    | ({
        relationTo: 'profile';
        value: string | Profile;
      } | null)
    | ({
        relationTo: 'fluegelanzahl';
        value: string | Fluegelanzahl;
      } | null)
    | ({
        relationTo: 'zusatzlichter';
        value: string | Zusatzlichter;
      } | null)
    | ({
        relationTo: 'oeffnungsarten';
        value: string | Oeffnungsarten;
      } | null)
    | ({
        relationTo: 'fensterformen';
        value: string | Fensterform;
      } | null)
    | ({
        relationTo: 'farben';
        value: string | Farben;
      } | null)
    | ({
        relationTo: 'dichtungsfarben';
        value: string | Dichtungsfarben;
      } | null)
    | ({
        relationTo: 'verglasungen';
        value: string | Verglasungen;
      } | null)
    | ({
        relationTo: 'schallschutz';
        value: string | Schallschutz;
      } | null)
    | ({
        relationTo: 'sicherheitsglas';
        value: string | Sicherheitsglas;
      } | null)
    | ({
        relationTo: 'glasdekore';
        value: string | Glasdekore;
      } | null)
    | ({
        relationTo: 'sprossen';
        value: string | Sprossen;
      } | null)
    | ({
        relationTo: 'extras';
        value: string | Extra;
      } | null)
    | ({
        relationTo: 'preisregeln';
        value: string | Preisregeln;
      } | null)
    | ({
        relationTo: 'rabattcodes';
        value: string | Rabattcode;
      } | null)
    | ({
        relationTo: 'anfragen';
        value: string | Anfragen;
      } | null)
    | ({
        relationTo: 'status_historie';
        value: string | StatusHistorie;
      } | null)
    | ({
        relationTo: 'rechnungen';
        value: string | Rechnungen;
      } | null)
    | ({
        relationTo: 'angebote';
        value: string | Angebote;
      } | null)
    | ({
        relationTo: 'reklamationen';
        value: string | Reklamationen;
      } | null)
    | ({
        relationTo: 'puck-templates';
        value: string | PuckTemplate;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  vorname?: T;
  nachname?: T;
  rolle?: T;
  stripe_customer_id?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "edit_history_select".
 */
export interface EditHistorySelect<T extends boolean = true> {
  collection?: T;
  doc_id?: T;
  event?: T;
  diff?: T;
  editor?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nummernkreise_select".
 */
export interface NummernkreiseSelect<T extends boolean = true> {
  typ?: T;
  jahr?: T;
  letzte_nummer?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email_queue_select".
 */
export interface EmailQueueSelect<T extends boolean = true> {
  event_type?: T;
  to?: T;
  subject?: T;
  html?: T;
  plain_text?: T;
  reply_to?: T;
  payload_data?: T;
  status?: T;
  attempts?: T;
  max_attempts?: T;
  next_retry_at?: T;
  idempotency_key?: T;
  error_log?: T;
  anfrage?: T;
  sent_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf_uploads_select".
 */
export interface PdfUploadsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produkttypen_select".
 */
export interface ProdukttypenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  erlaubte_materialien?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materialien_select".
 */
export interface MaterialienSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  lieferzeit_wochen?: T;
  garantie_jahre?: T;
  erlaubte_profile?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name_technisch?: T;
  name_einfach?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  qualitaetsstufe?: T;
  technische_daten?:
    | T
    | {
        uw_wert?: T;
        kammern?: T;
        bautiefe_mm?: T;
        dichtungen?: T;
      };
  masse?:
    | T
    | {
        min_breite_mm?: T;
        max_breite_mm?: T;
        min_hoehe_mm?: T;
        max_hoehe_mm?: T;
      };
  material?: T;
  erlaubte_produkttypen?: T;
  erlaubte_fensterformen?: T;
  erlaubte_fluegelanzahl?: T;
  erlaubte_oeffnungsarten?: T;
  erlaubte_zusatzlichter?: T;
  erlaubte_farben?: T;
  erlaubte_dichtungsfarben?: T;
  erlaubte_verglasungen?: T;
  erlaubte_schallschutz?: T;
  erlaubte_sicherheitsglas?: T;
  erlaubte_glasdekore?: T;
  erlaubte_sprossen?: T;
  erlaubte_extras?: T;
  last_edited_by?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fluegelanzahl_select".
 */
export interface FluegelanzahlSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  anzahl?: T;
  fuer_produkttypen?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zusatzlichter_select".
 */
export interface ZusatzlichterSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  kombinierbar_mit?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oeffnungsarten_select".
 */
export interface OeffnungsartenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  fuer_fenster?: T;
  fuer_balkontuer?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fensterformen_select".
 */
export interface FensterformenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  erlaubte_fluegelanzahl?: T;
  erlaubte_oeffnungsarten?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "farben_select".
 */
export interface FarbenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kategorie?: T;
  ral_code?: T;
  farb_code?: T;
  bild?: T;
  fuer_aussen?: T;
  fuer_innen?: T;
  erlaubte_materialien?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dichtungsfarben_select".
 */
export interface DichtungsfarbenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  farb_code?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verglasungen_select".
 */
export interface VerglasungenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  ug_wert?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schallschutz_select".
 */
export interface SchallschutzSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  schallschutzklasse?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sicherheitsglas_select".
 */
export interface SicherheitsglasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  typ?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glasdekore_select".
 */
export interface GlasdekoreSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sprossen_select".
 */
export interface SprossenSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  typ?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extras_select".
 */
export interface ExtrasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  beschreibung?: T;
  bild?: T;
  kategorie?: T;
  aufpreis?: T;
  aktiv?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preisregeln_select".
 */
export interface PreisregelnSelect<T extends boolean = true> {
  name?: T;
  produkttyp?: T;
  material?: T;
  profil?: T;
  grundpreis_pro_m2?: T;
  aufpreis_typ?: T;
  aufpreis_wert?: T;
  beschreibung?: T;
  aktiv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rabattcodes_select".
 */
export interface RabattcodesSelect<T extends boolean = true> {
  code?: T;
  beschreibung?: T;
  typ?: T;
  wert?: T;
  min_bestellwert?: T;
  gueltig_von?: T;
  gueltig_bis?: T;
  max_nutzungen?: T;
  aktuelle_nutzungen?: T;
  aktiv?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anfragen_select".
 */
export interface AnfragenSelect<T extends boolean = true> {
  anfrage_nummer?: T;
  status?: T;
  last_status_change_at?: T;
  produkte?:
    | T
    | {
        produkttyp?: T;
        material?: T;
        profil?: T;
        masse_breite?: T;
        masse_hoehe?: T;
        fluegelanzahl?: T;
        farbe_aussen?: T;
        farbe_innen?: T;
        verglasung?: T;
        weitere_optionen?: T;
        stueckzahl?: T;
        einzelpreis?: T;
        konfiguration_snapshot?: T;
        id?: T;
      };
  kontaktdaten?:
    | T
    | {
        vorname?: T;
        nachname?: T;
        email?: T;
        telefon?: T;
        strasse?: T;
        plz?: T;
        ort?: T;
        nachricht?: T;
      };
  gesamtpreis?: T;
  rabattcode?: T;
  hersteller_bestellnummer?: T;
  lieferdatum_erwartet?: T;
  hersteller_notizen?: T;
  hersteller_antwort?: T;
  stornierung_grund?: T;
  rueckerstattung_betrag?: T;
  rueckerstattung_status?: T;
  _status_kommentar?: T;
  interne_notizen?: T;
  version?: T;
  stripe_checkout_url?: T;
  stripe_session_id?: T;
  stripe_payment_intent_id?: T;
  stripe_payment_status?: T;
  stripe_expires_at?: T;
  stripe_refunded_amount_cents?: T;
  agb_akzeptiert_am?: T;
  agb_akzeptiert_bei_annahme_am?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status_historie_select".
 */
export interface StatusHistorieSelect<T extends boolean = true> {
  anfrage?: T;
  von_status?: T;
  zu_status?: T;
  geaendert_von?: T;
  zeitpunkt?: T;
  kommentar?: T;
  anhaenge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechnungen_select".
 */
export interface RechnungenSelect<T extends boolean = true> {
  typ?: T;
  nummer?: T;
  anfrage?: T;
  anfrage_nummer?: T;
  pdf?: T;
  betrag_netto_cents?: T;
  betrag_brutto_cents?: T;
  mwst_cents?: T;
  mwst_satz?: T;
  original_rechnung?: T;
  original_rechnung_nummer?: T;
  original_rechnung_datum?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote_select".
 */
export interface AngeboteSelect<T extends boolean = true> {
  nummer?: T;
  version?: T;
  anfrage?: T;
  anfrage_nummer?: T;
  status?: T;
  gueltig_bis?: T;
  freitext?: T;
  pdf?: T;
  betrag_netto_cents?: T;
  betrag_brutto_cents?: T;
  mwst_cents?: T;
  mwst_satz?: T;
  preisanpassung_begruendung?: T;
  preisanpassung_positionen?: T;
  rabatt_cents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reklamationen_select".
 */
export interface ReklamationenSelect<T extends boolean = true> {
  anfrage?: T;
  beschreibung?: T;
  fotos?: T;
  status?: T;
  loesung?: T;
  erstellt_von?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "puck-templates_select".
 */
export interface PuckTemplatesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  category?: T;
  content?: T;
  thumbnail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageLayout?: T;
  editorVersion?: T;
  isHomepage?: T;
  puckData?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
        nofollow?: T;
        excludeFromSitemap?: T;
      };
  conversionTracking?:
    | T
    | {
        isConversionPage?: T;
        conversionType?: T;
        conversionValue?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  links?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  firmenname?: string | null;
  adresse?: string | null;
  telefon?: string | null;
  email?: string | null;
  legal_links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  firmenname?: string | null;
  adresse_strasse?: string | null;
  adresse_hausnummer?: string | null;
  adresse_plz?: string | null;
  adresse_ort?: string | null;
  telefon?: string | null;
  email?: string | null;
  steuernummer?: string | null;
  ust_id?: string | null;
  bank_iban?: string | null;
  bank_bic?: string | null;
  bank_name?: string | null;
  mwst_satz: number;
  preisanzeige?: ('brutto' | 'netto') | null;
  stripe_zahlungslink_ablauf_stunden?: number | null;
  stripe_waehrung?: ('eur' | 'usd' | 'pyg') | null;
  angebots_gueltigkeit_tage?: number | null;
  widerrufsbelehrung?: string | null;
  agb_link?: string | null;
  agb_pdf?: (string | null) | Media;
  pdf_logo?: (string | null) | Media;
  email_absender_name?: string | null;
  email_reply_to?: string | null;
  email_signatur?: string | null;
  /**
   * Komma-getrennte E-Mail-Adressen fuer Mitarbeiter-Benachrichtigungen
   */
  benachrichtigungs_emails?: string | null;
  /**
   * Pro Event+Empfaenger aktivieren/deaktivieren (JSON)
   */
  email_event_toggles?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  zuletzt_aktualisiert_am?: string | null;
  zuletzt_aktualisiert_von?: (string | null) | User;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  firmenname?: T;
  adresse?: T;
  telefon?: T;
  email?: T;
  legal_links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  firmenname?: T;
  adresse_strasse?: T;
  adresse_hausnummer?: T;
  adresse_plz?: T;
  adresse_ort?: T;
  telefon?: T;
  email?: T;
  steuernummer?: T;
  ust_id?: T;
  bank_iban?: T;
  bank_bic?: T;
  bank_name?: T;
  mwst_satz?: T;
  preisanzeige?: T;
  stripe_zahlungslink_ablauf_stunden?: T;
  stripe_waehrung?: T;
  angebots_gueltigkeit_tage?: T;
  widerrufsbelehrung?: T;
  agb_link?: T;
  agb_pdf?: T;
  pdf_logo?: T;
  email_absender_name?: T;
  email_reply_to?: T;
  email_signatur?: T;
  benachrichtigungs_emails?: T;
  email_event_toggles?: T;
  zuletzt_aktualisiert_am?: T;
  zuletzt_aktualisiert_von?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}